displayName=Scuffed Clan Events
author=ThePrestiege
description=An example greeter plugin
tags=
plugins=com.scuffedclanevents.ScuffedClanEventsPlugin
support=https://github.com/camjewell11/ScuffedClanEvents